[file-paths]
input-sam = "/media/aaron/T9/HGT/testing/PB644_EB813.hifi_reads.sam"

[settings]
min-matched-frags = 5 # Note if this is greater than frags-per-seq, there will be no valid results.
frags-per-seq = 5


[minimap2]
# Do not include filepaths or output redirects.
# --sam-hit-only and -a (SAM output) is enabled by default and may not be disabled.

# Example:
# options = "-t 5 -I 1G -K 200M -w 25 -x map-hifi"
options = "-t 5 -I 1G -K 200M -w 25 -x map-hifi"
reference-file = "/media/aaron/T9/all_bacteria.fasta.gz"